### PR TITLE
Fixed qfp, tqfp, and lqfp `padContactLength`, and updated test snapshots

### LINKED ISSUE #207: QFP model looks very wrong
Image

### PR DESCRIPTION
**Pull request by rushabhcodes**
This pull request updates the QFP, LQFP, and TQFP chip rendering components in the `lib/qfp.tsx`, `lib/lqfp.tsx`, and `lib/tqfp.tsx` files. The main goal is to improve the accuracy of the chip body and lead placements, as well as to refine some physical parameters for better visual fidelity and consistency with real-world packages.

**Chip lead and body placement adjustments:**

* Increased the offset for lead positions on all four sides in both `LQFP` and `QFP` components, resulting in more accurate placement of leads relative to the chip body. (`lib/lqfp.tsx` [[1]](diffhunk://#diff-e2aaaf7029c344637e3889a16c67bd876f14a66fc3f231fb9e0d0f3bf92d9cceL43-R43) [[2]](diffhunk://#diff-e2aaaf7029c344637e3889a16c67bd876f14a66fc3f231fb9e0d0f3bf92d9cceL61-R61) [[3]](diffhunk://#diff-e2aaaf7029c344637e3889a16c67bd876f14a66fc3f231fb9e0d0f3bf92d9cceL80-R80) [[4]](diffhunk://#diff-e2aaaf7029c344637e3889a16c67bd876f14a66fc3f231fb9e0d0f3bf92d9cceL98-R98); `lib/qfp.tsx` [[5]](diffhunk://#diff-9011c2de31ee473491158b3220977f8995bcba14b539fb9a0d666861acb6116eL40-R40) [[6]](diffhunk://#diff-9011c2de31ee473491158b3220977f8995bcba14b539fb9a0d666861acb6116eL58-R58) [[7]](diffhunk://#diff-9011c2de31ee473491158b3220977f8995bcba14b539fb9a0d666861acb6116eL77-R77) [[8]](diffhunk://#diff-9011c2de31ee473491158b3220977f8995bcba14b539fb9a0d666861acb6116eL95-R95)
* Adjusted the calculation for `bodyDistance` in both `LQFP` and `QFP` to increase the spacing between the body and leads. (`lib/lqfp.tsx` [[1]](diffhunk://#diff-e2aaaf7029c344637e3889a16c67bd876f14a66fc3f231fb9e0d0f3bf92d9cceL34-R34); `lib/qfp.tsx` [[2]](diffhunk://#diff-9011c2de31ee473491158b3220977f8995bcba14b539fb9a0d666861acb6116eL31-R31)

**Chip body rendering improvements:**

* Changed the Z-center position for the chip body in all three components to be at `z: 0` instead of offset by half the lead thickness, improving vertical alignment. (`lib/lqfp.tsx` [[1]](diffhunk://#diff-e2aaaf7029c344637e3889a16c67bd876f14a66fc3f231fb9e0d0f3bf92d9cceL110-R110); `lib/qfp.tsx` [[2]](diffhunk://#diff-9011c2de31ee473491158b3220977f8995bcba14b539fb9a0d666861acb6116eL107-R112); `lib/tqfp.tsx` [[3]](diffhunk://#diff-50195257c8f77d50ad818d4f7e49aeebb77bff5eec212f4a3d4466954717f9afL93-R97)
* Updated chamfer size and taper ratio values for `QFP` and `TQFP` bodies for more realistic edge beveling. (`lib/qfp.tsx` [[1]](diffhunk://#diff-9011c2de31ee473491158b3220977f8995bcba14b539fb9a0d666861acb6116eL107-R112); `lib/tqfp.tsx` [[2]](diffhunk://#diff-50195257c8f77d50ad818d4f7e49aeebb77bff5eec212f4a3d4466954717f9afL93-R97)

**Physical parameter refinements:**

* Modified the default lead height for `TQFP` to match more typical package specifications. (`lib/tqfp.tsx` [lib/tqfp.tsxL15-R15](diffhunk://#diff-50195257c8f77d50ad818d4f7e49aeebb77bff5eec212f4a3d4466954717f9afL15-R15))
* Refined the pad contact length logic in `QFP` to provide more accurate values based on pin count, improving footprint generation. (`lib/qfp.tsx` [lib/qfp.tsxL140-R150](diffhunk://#diff-9011c2de31ee473491158b3220977f8995bcba14b539fb9a0d666861acb6116eL140-R150))

## Before:
image

## After:
Screenshot_20251109_151100

/fix #207

### CODE REVIEW

File: lib/tqfp.tsx [hunk 1]
```diff
@@ -90,11 +90,11 @@ export const TQFP = () => {
       ))}
 
       <ChipBody
-        center={{ x: 0, y: 0, z: leadThickness / 2 }}
```
Comment (rushabhcodes) [inline lib/tqfp.tsx]: @techmannih That height issue has been fixed with this pr, it was due to `z: leadThickness / 2`
